---
title: "Legionella delay"
author: "Dan Weinberger"
date: '2022-08-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(dplyr)
library(reshape2)
library(rjags)
library(stringr)
library(gtools)
#install.packages("hydroTSM")

library(HDInterval)


library(hydroTSM)
```


```{r}
set.seed(123)
df1  <- cbind.data.frame('dates'=seq.Date(from=as.Date('2012-01-01'), length.out = 365, by='day'))

df1 <- df1 %>%
  mutate(t=row_number(), 
         sin1= 2*sin(2*pi*t/365),
         month = as.factor(month(dates)),
         N_exposures = rpois(length(dates), exp(1 + 0.3*sin1 + rnorm(length(dates),0,0.75))  ) )
month.mat <- model.matrix(~0 + month, data=df1)
month.mat <- month.mat[,2:12]

plot(df1$N_exposures)
```



```{r}
model_string <- "
model{
for(t in 1:N_times){ 
  N_cases[t] ~ dpois(lambda[t])
  
  log(lambda[t]) <- int  +  alpha[t] +  month.mat %*% beta  + log_acm_noj

} 
  

  int ~ dnorm(0, 1e-4)
  
  for( t in 1: N.pre.times){
  alpha[t] = 0
  }
  
 alpha[(N.pre.times+1)] ~ dnorm(0, (1-rho2^2)/tau2.alpha)

 for( t in (N.pre.times+1):N_times ){
  alpha[t] ~ dnorm(rho2*alpha[t-1],tau2.alpha)
 }
 
 for(k in 1:11){
  beta[k] ~ dnorm(0,1e-4)
 }

    tau2.alpha ~ dgamma(0.01,0.01)

    rho2 ~ dunif (-1,1)

}
"



##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')


##############################################
#Model Organization
##############################################
model_spec<-textConnection(model_string)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('N_cases'=observed_ts$N_cases,
                                 'N_times'=365, #could use whole dataset but would take a long time
                                  'monthmat'=month.mat
                                    ),
                       n.adapt=10000, 
                       n.chains=3)


params<-c('lambda', 'alpha', 'beta','epsilon', 'rho2')

##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=10000)

posterior_samples.all<-do.call(rbind,posterior_samples)
#post1.summary<-summary(posterior_samples)
#post_means<-colMeans(posterior_samples.all)
post_means<-apply(posterior_samples.all, 2, mean)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
#ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
ci<-matrix(ci, ncol=2)

row.names(ci)<-sample.labs
#post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs

indices <- str_extract_all(names(post_means), "(?<=\\[).+?(?=\\])")
rep1 <- sapply(indices, function(x) identical(x, character(0))) #is it missing ie character(0)
indices[which(rep1==1)] <- '999'


index_n <- as.numeric(unlist(indices))

combined <- cbind.data.frame(post_means, ci,index_n )
names(combined) <- c('mean','lcl','ucl','index_t')

post_epsilon <- combined[grep('epsilon',names(post_means)),]

post_lambda <- combined[grep('lambda',names(post_means)),]

#model vs observed TS
plot(observed_ts$N_cases[1:365], type='l')
points(post_epsilon$index_t, post_epsilon$mean, type='l' ,col='red')
points(post_lambda$index_t,post_lambda$mean, type='l' ,col='blue')

#model vs true exposure TS

plot(df1$N_exposures[1:365], type='l')
points(post_epsilon$index_t, post_epsilon$mean, type='l' ,col='red')
points(post_lambda$index_t,post_lambda$mean, type='l' ,col='blue')

str(posterior_samples.all)
```

```{r}
post_beta <- combined[grep('beta',names(post_means)),]


plot(rain_weights, type='l')
points(cumsum(post_beta$mean), type='l', col='red')

plot(rain_weights, type='l')
points(post_beta$mean, type='l', col='red')
#

beta_samps <- posterior_samples.all[1:1000,grep('beta',names(post_means))]
matplot(t(beta_samps), type='l')
```


Posteriors
```{r}
plot(posterior_samples.all[,'alpha[35]'], type='l')
plot(posterior_samples.all[,'lambda[35]'], type='l')

plot(posterior_samples.all[,'delay_est[10]'], type='l')

plot(posterior_samples.all[,'beta[4]'], type='l')


```

```{r}
post_delay_est <- combined[grep('delay_est',names(post_means)),]

plot(post_delay_est$mean, type='l', ylim=c(0,1))
points(delay_dist, type='l', lty=2, lwd=2, col='red')


post_samples_delay <- posterior_samples.all[,grep('delay_est',names(post_means))]

apply(post_samples_delay[1:100,],1,sum)

matplot(t(post_samples_delay[1:2000,]), type='l')
points(delay_dist, col='red', lwd=2, lty=2, type='l')

```



