---
title: "JAGS_10Oct22"
output: html_document
date: "2022-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(dplyr)
library(reshape2)
library(rjags)
library(stringr)
library(gtools)
#install.packages("hydroTSM")
library(HDInterval)
library(hydroTSM)
```


Delay Dist 
```{r}
x <- seq(0, 20, by=1)
delay_dist = dgamma(x, shape = 4.96, scale = 1.27, log = FALSE)

```

Case Import 
```{r}
case.df = read.csv("~/Documents/IncubationPeriod_Analysis/EventInformationExtract_2011_2021.csv")
case.df$ddate = as.Date(case.df$EVENT_DATE, format = '%m/%d/%y')

# subset only symptom onset
case.df = case.df[(case.df$EVENT_TYPE == 'SYMPTOM_ONSET_DATE'),] # 861 
case.df$case1 = 1
case.df.1 = setNames(aggregate(case.df$case1 ~ case.df$ddate, FUN = 'sum'), c("ddate", "case_sum"))
case.dates <- cbind.data.frame('dates'=seq.Date(from=as.Date('2011-01-01'), to=as.Date('2021-12-31'), by='day'))
case.df = merge(case.dates, case.df.1, by.x = 'dates', by.y = 'ddate', all.x = T)
case.df$case_sum = ifelse(is.na(case.df$case_sum), 0, case.df$case_sum)
# max is 6 cases in one day 
zero = case.df[(case.df$case_sum == 0),] # 3327 days have a zero value;  82% of days have zero 


```


Weather import 

```{r}
weather.d = read.csv("Data/weather_agg_rain_state.csv")
weather.d = read.csv("Data/weather_agg_humidity_state.csv")
weather.d = read.csv("weather_7years.csv")

weather.d$ddate = as.Date(as.character(weather.d$date1))

# weather.d$Reported_PrecipSum = ifelse(weather.d$Temp_Mean < 32, 0, weather.d$Reported_PrecipSum)
# weather.d = weather.d[(weather.d$ddate < '2019-01-01' & weather.d$ddate > '2017-12-31'),]

weather.d$rain0 = weather.d$Precip_Sum_Calc
weather.d = as.data.frame(weather.d[,c(5,6)])


```


Make observed TS with sin and cos vars 
```{r}

observed_ts = merge(case.df,weather.d, by.y = 'ddate', by.x = 'dates', all.x = T)
observed_ts$t = 1:nrow(observed_ts)
observed_ts$sin1 = cos(2*pi*observed_ts$t/365)
observed_ts$cos1 = cos(2*pi*observed_ts$t/365)
observed_ts$N_cases = observed_ts$case_sum

```

Dan's code originally had this: 
   log.int ~ dnorm(0, 1e-4)
   int <- exp(log.int)

```{r}
model_string <- "
model{
for(t in 37:N_times){ #22 lag from linking epsilon to lambda, and 15 lag from linking rainfall to epsilon
  N_cases[t] ~ dpois(lambda[t])
  
  lambda[t] <- (epsilon[t]*delay_dist[1] + 
               epsilon[t- 1 ]*delay_dist[2] + 
               epsilon[t- 2 ]*delay_dist[3] +
               epsilon[t- 3 ]*delay_dist[4] + 
               epsilon[t- 4 ]*delay_dist[5] +
               epsilon[t- 5 ]*delay_dist[6] + 
               epsilon[t- 6 ]*delay_dist[7] +
               epsilon[t- 7 ]*delay_dist[8] + 
               epsilon[t- 8 ]*delay_dist[9] +
               epsilon[t- 9 ]*delay_dist[10] + 
               epsilon[t- 10 ]*delay_dist[11] +
               epsilon[t- 11 ]*delay_dist[12] + 
               epsilon[t- 12 ]*delay_dist[13] +
               epsilon[t- 13 ]*delay_dist[14] + 
               epsilon[t- 14 ]*delay_dist[15] +
               epsilon[t- 15 ]*delay_dist[16] + 
               epsilon[t- 16 ]*delay_dist[17] +
               epsilon[t- 17 ]*delay_dist[18] +
               epsilon[t- 18 ]*delay_dist[19] +
               epsilon[t- 19 ]*delay_dist[20] +
               epsilon[t- 20 ]*delay_dist[21] )
            
} 
  for(t in 15:N_times){
      epsilon[t] <- (int +  rain[t]*beta[1] +  rain[t-1]*beta[2]  +   rain[t-2]*beta[3]
       +  rain[t-3]*beta[4] +  rain[t-4]*beta[5] +  rain[t-5]*beta[6] +  rain[t-6]*beta[7] +  rain[t-7]*beta[8]
        +  rain[t-8]*beta[9] +  rain[t-9]*beta[10] + rain[t-10]*beta[11] +  rain[t-11]*beta[12] + rain[t-12]*beta[13]
        + rain[t-13]*beta[14] +  rain[t-14]*beta[15] 
        + delta[1]*sin1[t] + delta[2]*cos1[t] )  
        
  }
   int ~ dnorm(0, 1e-4)
   
   
 for(i in 1:15){
  log.beta[i] ~ dnorm(0, tau3.beta) #shrinkage prior
 }
 for(i in 1:15){
    beta[i] <- exp(log.beta[i])
 }
  
   for(k in 1:2){
    delta[k] ~ dnorm(0,1e-4)
   }
  
     tau3.beta ~ dgamma(0.01,0.01)
    
}
"
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')
##############################################
#Model Organization
##############################################
model_spec<-textConnection(model_string)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('N_cases'=observed_ts$N_cases,
                                 'N_times'=1095, #could use whole dataset but would take a long time
                                                       'delay_dist'=delay_dist,
                                 'sin1' = observed_ts$sin1,
                                 'cos1' = observed_ts$cos1,
                                 'rain'=observed_ts$rain0
                                    ),
                       n.adapt=10000, 
                       n.chains=3)
params<-c('lambda', 'beta','epsilon', 'tau3.beta', 'int', 'delta')
##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=10000)
posterior_samples.all<-do.call(rbind,posterior_samples)
#post1.summary<-summary(posterior_samples)
#post_means<-colMeans(posterior_samples.all)
post_means<-apply(posterior_samples.all, 2, mean)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
#ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
ci<-matrix(ci, ncol=2)
row.names(ci)<-sample.labs
#post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs
indices <- str_extract_all(names(post_means), "(?<=\\[).+?(?=\\])")
rep1 <- sapply(indices, function(x) identical(x, character(0))) #is it missing ie character(0)
indices[which(rep1==1)] <- '999'
index_n <- as.numeric(unlist(indices))
combined <- cbind.data.frame(post_means, ci,index_n )
names(combined) <- c('mean','lcl','ucl','index_t')
post_epsilon <- combined[grep('epsilon',names(post_means)),]
post_lambda <- combined[grep('lambda',names(post_means)),]
#model vs observed TS
plot(observed_ts$N_cases[1:1095], type='l')
points(post_epsilon$index_t, post_epsilon$mean, type='l' ,col='red')
points(post_lambda$index_t,post_lambda$mean, type='l' ,col='blue') # lambda should be the exposure dates? 
#model vs true exposure TS
plot(df1$N_exposures[1:365], type='l')
points(post_epsilon$index_t, post_epsilon$mean, type='l' ,col='red')
points(post_lambda$index_t,post_lambda$mean, type='l' ,col='blue')
saveRDS(posterior_samples.all,'./Results/posteriors_exp.rds')


```

```{r}
str(posterior_samples.all)
plot(posterior_samples.all[,"beta[1]"], type='l')
plot(posterior_samples.all[,"int"], type='l')
plot(posterior_samples.all[,"beta[2]"])
```

```{r}
post_beta <- combined[grep('beta[',names(post_means), fixed=T),]

plot(post_beta$mean, type='l', col='red')
points(post_beta$lcl, type='l', col='red', lty=3)
points(post_beta$ucl, type='l', col='red', lty=3)
#
beta_samps <- posterior_samples.all[0001:5000,grep('beta[',names(post_means), fixed=T)]
matplot(t(beta_samps), type='l', ylim=c(-0.1, 0.3))
points(rain_weights, type='l')
```


Posteriors
```{r}
plot(posterior_samples.all[,'alpha[35]'], type='l')
plot(posterior_samples.all[,'lambda[35]'], type='l')
#plot(posterior_samples.all[,'delay_est[10]'], type='l')
plot(posterior_samples.all[,'beta[4]'], type='l')
```

```{r}
post_delay_est <- combined[grep('delay_est',names(post_means)),]
plot(post_delay_est$mean, type='l', ylim=c(0,1))
points(delay_dist, type='l', lty=2, lwd=2, col='red')
post_samples_delay <- posterior_samples.all[,grep('delay_est',names(post_means))]
apply(post_samples_delay[1:100,],1,sum)
matplot(t(post_samples_delay[1:2000,]), type='l')
points(delay_dist, col='red', lwd=2, lty=2, type='l')
```






































